/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  // To add an external link to the Java docs, we had to switch to a manually defined sidebar for the references section.
  tutorialSidebar: [
    'Overview',
    {type: 'html', value: '<hr class="margin-vert--sm">'},
    {type: 'html', value: '<p class="sidebar-title margin--none"><i class="fa fa-rocket" aria-hidden="true"></i>Get started</p>'},
    {type: 'autogenerated', dirName: 'get_started'},
    {
      type: 'link',
      label: 'Examples',
      href: 'https://github.com/restatedev/examples',
    },
    {type: 'html', value: '<hr class="margin-vert--sm">'},
    {type: 'html', value: '<p class="sidebar-title margin--none">Develop</p>'},
    {type: 'autogenerated', dirName: 'develop'},
    {type: 'html', value: '<p class="sidebar-title margin--none">Deploy</p>'},
    {type: 'autogenerated', dirName: 'deploy'},
    {type: 'html', value: '<p class="sidebar-title margin--none">Operate</p>'},
    {type: 'autogenerated', dirName: 'operate'},
    {type: 'html', value: '<hr class="margin-vert--sm">'},
    {type: 'html', value: '<p class="sidebar-title margin--none">API References</p>'},
    {type: 'autogenerated', dirName: 'references'},
    {
      type: 'link',
      label: 'Java Docs',
      href: 'https://javadoc.io/doc/dev.restate',
    },
  ],
};

module.exports = sidebars;
