/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  // To add an external link to the Java docs, we had to switch to a manually defined sidebar for the references section.
  tutorialSidebar: [
    'Overview',
    {type: 'category', label: 'Get started', items: [
        {type: 'autogenerated', dirName: 'get_started'},
        {
          type: 'link',
          label: 'Examples',
          href: 'https://github.com/restatedev/examples',
        },
      ]
    },
    {type: 'category', label: 'SDKs', items: [{type: 'autogenerated', dirName: 'services'}]},
    {type: 'category', label: 'Restate', items: [{type: 'autogenerated', dirName: 'restate'}]},
    {
      type: 'category',
      label: 'References',
      items: [
        {type: 'autogenerated', dirName: 'references'},
        {
          type: 'link',
          label: 'Java Docs',
          href: 'https://javadoc.io/doc/dev.restate',
        },
      ]
    },
  ],
};

module.exports = sidebars;
