package develop;

import dev.restate.sdk.Service;
import dev.restate.sdk.http.vertx.RestateHttpEndpointBuilder;

import java.util.concurrent.Executors;

class ServingVirtualThreads {
    public void virtualThreads(RestateHttpEndpointBuilder builder) {
        // <start_here>
        builder.bind(
            // This is the class generated by the annotation processor
            new GreeterBindableService(
                new Greeter(),
                new Service.Options(Executors.newVirtualThreadPerTaskExecutor())
            )
        );
        // <end_here>
    }
}
