package develop

import dev.restate.sdk.http.vertx.RestateHttpEndpointBuilder
import dev.restate.sdk.kotlin.Service
import java.util.concurrent.Executors
import kotlinx.coroutines.asCoroutineDispatcher

class ServingVirtualThreads {
    fun virtualThreads(builder: RestateHttpEndpointBuilder) {
        // <start_here>
        builder.bind(
            // This is the class generated by the annotation processor
            GreeterBindableService(
                Greeter(),
                Service.Options(
                    coroutineContext = Executors.newVirtualThreadPerTaskExecutor().asCoroutineDispatcher()
                )
            )
        )
        // <end_here>
    }
}
