name: "Install protoc"
description: "Installs protoc for the given os"
inputs:
  protoc-version:
    description: "protoc version"
    required: false
    default: "21.12"
runs:
  using: "composite"
  steps:
    - name: Install protoc for ${{ runner.os }}
      env:
        LINK: https://github.com/protocolbuffers/protobuf/releases/download
        PROTOC_VERSION: ${{ inputs.protoc-version }}
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          PROTOC_ZIP=protoc-$PROTOC_VERSION-linux-x86_64.zip
        elif [ "$RUNNER_OS" == "macOS" ]; then
          PROTOC_ZIP=protoc-$PROTOC_VERSION-osx-x86_64.zip
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi
        curl -OL $LINK/v$PROTOC_VERSION/$PROTOC_ZIP
        unzip -o $PROTOC_ZIP -d $HOME/.local bin/protoc
        unzip -o $PROTOC_ZIP -d $HOME/.local 'include/*'
        rm -f $PROTOC_ZIP
        echo "$HOME/.local" >> $GITHUB_PATH
        chmod +x $HOME/.local/bin/protoc
        echo "PROTOC=$HOME/.local/bin/protoc" >> $GITHUB_ENV
        echo "PROTOC_INCLUDE=$HOME/.local/include" >> $GITHUB_ENV
      shell: bash
