roles = [
    "worker",
    "admin",
    "metadata-store",
]
cluster-name = "localcluster"
allow-bootstrap = true
metadata-store-address = "http://127.0.0.1:5123/"
bind-address = "0.0.0.0:5122"
advertised-address = "http://127.0.0.1:5122/"
bootstrap-num-partitions = 24
shutdown-timeout = "1m"
tracing-filter = "info"
log-filter = "warn,restate=info"
log-format = "pretty"
log-disable-ansi-codes = false
connect-timeout = "10s"
disable-prometheus = false
rocksdb-total-memory-size = "6.0 GB"
rocksdb-total-memtables-ratio = 0.5
rocksdb-high-priority-bg-threads = 2
rocksdb-write-stall-threshold = "3s"
rocksdb-enable-stall-on-memory-limit = false
rocksdb-perf-level = "enable-count"

[http-keep-alive-options]
interval = "40s"
timeout = "20s"

[worker]
internal-queue-length = 10000

[worker.storage]
rocksdb-disable-wal = true
rocksdb-memory-ratio = 0.49000000953674316
persist-lsn-interval = "1h"
persist-lsn-threshold = 1000

[worker.invoker]
inactivity-timeout = "1m"
abort-timeout = "1m"
message-size-warning = "10.0 MB"
concurrent-invocations-limit = 10000

[worker.invoker.retry-policy]
type = "exponential"
initial-interval = "50ms"
factor = 2.0
max-interval = "10s"

[admin]
bind-address = "0.0.0.0:9070"
heartbeat-interval = "1s 500ms"
log-trim-interval = "1h"
log-trim-threshold = 1000

[admin.query-engine]
memory-size = "4.0 GB"
pgsql-bind-address = "0.0.0.0:9071"

[ingress]
bind-address = "0.0.0.0:8080"
kafka-clusters = []

[bifrost]
default-provider = "local"

[bifrost.local]
rocksdb-disable-wal = false
rocksdb-memory-ratio = 0.5
rocksdb-disable-wal-fsync = false
writer-batch-commit-count = 5000
writer-batch-commit-duration = "0s"

[metadata-store]
bind-address = "0.0.0.0:5123"
request-queue-length = 32
rocksdb-memory-ratio = 0.009999999776482582

[metadata-store.rocksdb]
rocksdb-disable-wal = false

