name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  doc-build:
    name: Documentation build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run vale spell and style check
        continue-on-error: true
        uses: errata-ai/vale-action@reviewdog
        with:
          files: docs

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build

  ts-build:
    name: TS snippets build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Compile TypeScript code snippets
        run: npm install --prefix code_snippets/ts && npm run build --prefix code_snippets/ts

      - name: Check if TypeScript code snippets build is successful
        run: |
          if [ -d "code_snippets/ts/dist" ]; then
          echo "TypeScript compilation successful"
          else
          echo "TypeScript compilation failed"
          exit 1
          fi

  python-build:
    name: Python snippets build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Test if Python code snippets compile
      - name: Install dependencies and check Python code snippets
        run: |
          cd code_snippets/python
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install mypy
          python3 -m mypy .
          deactivate

  java-build:
    name: Java snippets build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup Java
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      # Check Java code snippets
      - name: Test Java code snippets
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          build-root-directory: code_snippets/java

  kotlin-build:
    name: Kotlin snippets build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup Java
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      # Check Kotlin code snippets
      - name: Test Kotlin code snippets
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          build-root-directory: code_snippets/kotlin

  go-build:
    name: Golang snippets build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Go
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      # Check Go code snippets
      - name: Test Go code snippets
        working-directory: code_snippets/go
        run: go test ./...

  rust-build:
    name: Rust snippets build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Rust
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          rustflags: ""

      # Run Rust tests
      - name: Run Rust tests
        run: cargo clippy --manifest-path ./code_snippets/rust/Cargo.toml