name: Test build

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run vale spell and style check
        uses: errata-ai/vale-action@reviewdog
        with:
          files: docs

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build
