name: Trigger release

on:
  workflow_dispatch:
    version:
      description: 'Documentation version (without prepending v).'
      required: true
      type: string

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production

      - name: Merge main -> production and tag it
        run: |
          git --version
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge main
          git tag v${{ inputs.version }}
          git push --follow-tags
